USE mydb;
SET SQL_SAFE_UPDATES = 0;



INSERT INTO music (idmusic, music_url, music_name, type) VALUES (1, 'https://ruo.morsmusic.org/load/892508633/The_Weeknd_-_Save_Your_Tears_(musmore.com).mp3', 'Save Your Tears - The Weeknd', 'calm');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (2, 'https://ruo.morsmusic.org/load/1367581502/Katy_Perry_-_Harleys_In_Hawaii_(musmore.com).mp3', 'Harleys In Hawaii - Katy Perry', 'calm');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (3, 'https://ruo.morsmusic.org/load/692527440/Kesha_-_TiK_ToK_(musmore.com).mp3', 'TiK ToK - Kesha', 'calm');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (4, 'https://ruo.morsmusic.org/load/254040542/Drake_-_Hotline_Bling_(musmore.com).mp3', 'Hotline Bling - Drake', 'calm');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (5, 'https://ruo.morsmusic.org/load/1491892143/Clean_Bandit_Jess_Glynne_-_Rather_Be_(musmore.com).mp3', 'Rather Be feat. Jess Glynne - Clean Bandit, Jess Glynne', 'calm');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (6, 'https://ruo.morsmusic.org/load/1611947332/Sam_Smith_-_Money_On_My_Mind_(musmore.com).mp3', 'Money On My Mind - Sam Smith', 'calm');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (7, 'https://www1.muzbears.ru/files/track/2022/11/rihanna-california-king-bed.mp3', 'California King Bed - Rihanna', 'calm');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (8, 'https://ruo.morsmusic.org/load/2096214590/Arctic_Monkeys_-_Snap_Out_Of_It_(musmore.com).mp3', 'Snap Out Of It - Arctic Monkeys', 'calm');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (9, 'https://ruo.morsmusic.org/load/1817605427/Daft_Punk_-_Around_The_World_(musmore.com).mp3', 'Around The WorldRadio Edit - Daft Punk', 'calm');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (10, 'https://ruo.morsmusic.org/load/421205759/Kanye_West_-_Good_Morning_(musmore.com).mp3', 'Good Morning - Kanye West', 'calm');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (11, 'https://ruo.morsmusic.org/load/686974148/Drowning_Pool_-_Bodies_(musmore.com).mp3', 'Bodies - Drowning Pool', 'calm');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (12, 'https://rmf.muzmo.cc/get/music/20200404/Yaeji_-_WAKING_UP_DOWN_69050945.mp3', 'WAKING UP DOWN - Yaeji', 'calm');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (13, 'https://ruo.morsmusic.org/load/1421839839/Avicii_-_Wake_Me_Up_(musmore.com).mp3', 'Wake Me Up Radio Edit - Avicii', 'calm');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (14, 'https://ruo.morsmusic.org/load/1552505937/The_Chemical_Brothers_-_The_Salmon_Dance_(musmore.com).mp3', 'The Salmon Dance - The Chemical Brothers', 'calm');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (15, 'https://ruo.morsmusic.org/load/17700286/Skrillex_Diplo_Jack_Justin_Bieber_-_Where_Are_Now_(musmore.com).mp3', 'Where Are U Now - Skrillex, Diplo, Justin Bieber', 'calm');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (16, 'https://ruo.morsmusic.org/load/388131828/Demi_Lovato_-_Confident_(musmore.com).mp3', 'Confident - Demi Lovato', 'calm');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (17, 'https://ruo.morsmusic.org/load/1730153353/Mike_Oldfield_-_Moonlight_Shadow_(musmore.com).mp3', 'Moonlight ShadowRemastered - Mike Oldfield', 'calm');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (18, 'https://ruo.morsmusic.org/load/1771255276/Korol_i_SHut_-_Ten_2_Dagon_(musmore.com).mp3', 'Король и Шут (КиШ) - Дагон', 'rock');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (19, 'https://ruo.morsmusic.org/load/1053535262/Korol_i_SHut_-_Kukla_kolduna_(musmore.com).mp3', 'Король и Шут (КиШ) - Кукла Колдуна', 'rock');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (20, 'https://ruo.morsmusic.org/load/1222822209/Korol_i_SHut_-_Grobovshhik_(musmore.com).mp3', 'Король и Шут (КиШ) - Гробовщик', 'rock');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (21, 'https://ruo.morsmusic.org/load/1571885557/Korol_i_SHut_-_Tanec_zlobnogo_geniya_(musmore.com).mp3', 'Король и Шут (КиШ) - Танец злобного гения', 'rock');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (22, 'https://ruo.morsmusic.org/load/1109591166/Korol_i_SHut_-_Prodavec_koshmarov_(musmore.com).mp3', 'Король и Шут (КиШ) - Продавец кошмаров', 'rock');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (23, 'https://ruo.morsmusic.org/load/1980259823/Korol_i_SHut_-_Vedma_i_Osel_(musmore.com).mp3', 'Король и Шут (КиШ) - Ведьма и осел', 'rock');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (24, 'https://ruo.morsmusic.org/load/536287624/Korol_i_SHut_-_Gorod_mertvecov_(musmore.com).mp3', 'Король и Шут (КиШ) - Город Мертвецов', 'rock');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (25, 'https://ruo.morsmusic.org/load/741670371/Korol_i_SHut_-_Paren_i_leshijj_(musmore.com).mp3', 'Король и Шут (КиШ) - Парень и леший', 'rock');
INSERT INTO music (idmusic, music_url, music_name, type) VALUES (26, 'https://ruo.morsmusic.org/load/264272420/Korol_i_SHut_-_Proklyatyjj_staryjj_dom_(musmore.com).mp3', 'Король и Шут (КиШ) - Проклятый старый дом', 'rock');

INSERT INTO task (task, type, level) VALUES ('Найдите значение выражения: 35 + 59 =', 'math', 'easy');
INSERT INTO task (task, type, level) VALUES ('Найдите значение выражения: 12 * (–9) =', 'math', 'easy');
INSERT INTO task (task, type, level) VALUES ('Найдите корни уравнения: x (x – 25) = 0', 'math', 'easy');
INSERT INTO task (task, type, level) VALUES ('Найдите значение выражения: 1574 + 357 =', 'math', 'hard');
INSERT INTO task (task, type, level) VALUES ('Приведите подобные слагаемые: 16a – 24b – 7a + 9b', 'math', 'hard');
INSERT INTO task (task, type, level) VALUES ('Какое название имеет функция: y = 45/3x', 'math', 'hard');
INSERT INTO task (task, type, level) VALUES ('Москву раньше называли белокаменной. А какой город называли черным', 'logic', 'easy');
INSERT INTO task (task, type, level) VALUES ('Каких камней нет в море?', 'logic', 'easy');
INSERT INTO task (task, type, level) VALUES ('Какой сказочный герой от рождения владел тремя языками?', 'logic', 'easy');
INSERT INTO task (task, type, level) VALUES ('Сколько раз цифра 9 встречается в ряду от одного до ста?', 'logic', 'hard');
INSERT INTO task (task, type, level) VALUES ('Отгадайте слово из 9 букв: а, м, т, с, о, н, р, о, г. Какая будет вторая буква в слове?', 'logic', 'hard');
INSERT INTO task (task, type, level) VALUES ('Какие два слова наиболее близки по значению: 1.улыбаться, 2.клеветать, 3.угодничать, 4.миловать, 5.лебезить, 6.хмуриться ?', 'logic', 'hard');

INSERT INTO answer (answer, correctness, task_idtask) VALUES ('81', 0, 1);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('94', 1, 1);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('76', 0, 1);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('85', 0, 1);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('-108', 1, 2);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('92', 0, 2);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('-88', 0, 2);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('75', 0, 2);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('0 и 2', 0, 3);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('2 и 5', 0, 3);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('0 и 25', 1, 3);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('5 и 12', 0, 3);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('1831', 0, 4);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('1931', 1, 4);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('1929', 0, 4);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('1829', 0, 4);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('парабола', 0, 5);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('экспонента', 0, 5);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('кубическая парабола', 0, 5);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('гипербола', 1, 5);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('10a – 16b', 0, 6);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('9a – 15b', 1, 6);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('9a', 0, 6);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('11a + 15b', 0, 6);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('Чердынь', 0, 7);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('Чернигов', 1, 7);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('Челябинск', 0, 7);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('Чебоксары', 0, 7);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('золотых', 0, 8);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('овальных', 0, 8);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('сухих', 1, 8);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('квадратных', 0, 8);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('змей-горыныч', 1, 9);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('водяной', 0, 9);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('кот в сапогах', 0, 9);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('тугарин змей', 0, 9);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('20', 1, 10);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('9', 0, 10);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('10', 0, 10);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('18', 0, 10);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('о', 0, 11);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('и', 0, 11);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('а', 1, 11);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('м', 0, 11);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('1 и 6', 0, 12);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('2 и 3', 0, 12);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('4 и 5', 0, 12);
INSERT INTO answer (answer, correctness, task_idtask) VALUES ('3 и 5', 1, 12);


INSERT INTO motivational_phrase (phrase) VALUES ('Не ждите. Время никогда не будет подходящим. | Наполеон Хилл');
INSERT INTO motivational_phrase (phrase) VALUES ('Усердно работайте, мечтайте по-крупному.');
INSERT INTO motivational_phrase (phrase) VALUES ('Мотивация - это то, что заставляет вас начать. Привычка - это то, что заставляет вас продолжать. | Джим Рюн');
INSERT INTO motivational_phrase (phrase) VALUES ('Вы должны выучить правила игры. А затем вы должны играть лучше, чем кто-либо другой. | Альберт Эйнштейн');
INSERT INTO motivational_phrase (phrase) VALUES ('Если вы потратите свою жизнь на то, чтобы быть лучшим во всем, вы никогда не станете великим ни в чем. | Том Рат');
INSERT INTO motivational_phrase (phrase) VALUES ('Мечтатели - это спасители мира. | Джеймс Алл');
INSERT INTO motivational_phrase (phrase) VALUES ('Я не знаю секрета успеха, но секрет неудачи - это попытка всем угодить. | Билл Косби');

